allowBuilds:
  '@logicflow/core': false
  '@parcel/watcher': false
  '@vue-office/docx': false
  '@vue-office/excel': false
  '@vue-office/pdf': false
  core-js-pure: false
  es5-ext: false
  vue-demi: false
  yorkie: false

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
